### ISSUE TITLE
Error when i't should just be a 403 message

### ISSUE THREAD

**Issue by magnolia61** [mlutfy/ca.bidon.reporterror#19] opened 2015-07-24 06:54 UTC
When someone clicks on a link in an email to a civicrm report and is nog logged in, an error mesage is generated. Is there a way to filter these out. It should just be 403's I guess. Or should this need changes in civicrm core not to throw a fatal error here?

***ERROR***
message:            We can't load the requested web page. This page requires cookies to be enabled in your browser settings. Please check this setting and enable cookies (if they are not enabled). Then try again. If this error persists, contact the site adminstrator for assistance.&lt;br /&gt;&lt;br /&gt;Site Administrators: This error may indicate that users are accessing this page using a domain or URL other than the configured Base URL. EXAMPLE: Base URL is http://example.org, but some users are accessing the page via http://www.example.org or a domain alias like http://myotherexample.org.&lt;br /&gt;&lt;br /&gt;Error type: Could not find a valid session key.

 [entryURL] => https://www.onvergetelijk.nl/civicrm/report/instance/362?reset=1
            [qfKey] => c7f76cbc8abb04b044cfb549b3cd2393_2419

**Comment by mlutfy** [comment] 2015-07-28 17:16
Is this error happening specifically when they have been logged out, but submitted a form that was still open in their browser? Normally the qfkey error should not happen unless they are submitting a form.

**Comment by mlutfy** [comment] 2016-03-06 18:58
I cannot reproduce this issue, and did not get a response, so closing the issue. Feel free to re-open if necessary.

**Closed by mlutfy** 2016-03-06 18:58 UTC
